### ISSUE TITLE
CSS Rationalization

### ISSUE THREAD

**Issue by samnabi** [robinsloan/perfect-edition#5]
Do you have any organizing principles in mind for rationalizing the CSS? Like, structured BEM-style class names vs lots of little utility classes?

**Comment by robinsloan** [comment]
I had to google "BEM-style" so that tells you something about where I'm at 😉

This is a good prompt to think through this. My unschooled instinct is to write fewer, larger classes, so I guess I'd rather refine that than start over with a totally different paradigm. At the same time, one of my core objectives is brevity -- I would like there to be as little CSS as possible, while still having it look great.

What else? I'd like to style plain HTML5 elements rather than use classes as much as possible. (In other projects, I have just invented elements pretty liberally, but never been sure about the pitfalls. This project only targets modern browsers, so maybe it would be fine?)

The basic organization of the CSS in the file is pretty jumbled; I'd like to move things around into logical sections with headings and a bit of description. `/* e-book control elements */, etc.

There are a few "magic numbers" in there, and quite a few `calc()` that produce good results but are totally "??!!" to look at. I'd like all of the layout calculations to be principled & readable (which probably calls for more commenting).

Finally, I'd say one bit of low-hanging fruit is my basically random use of ids in a few places, rather classes or elements; I should probably go through & change those to something else.

Let me know if that's helpful at all.
